### ISSUE TITLE
مشاكل في قبول الترجمة الصحيحة من الخاطئة

### ISSUE THREAD

**Issue by Taki3600** [simplicialsoftware/nebulous-translations#817]
@grog444 

ارى انك تعتمد على ترجمة قوقل الخاطئة
وبعض اللاعبين الذي فقط يقومون بإضافة تشكيلات لا داعي لها مثل (الهمزة_والتنوين) 
فكلما اقوم بترجمة صحيحة يتم تجاهلها واغلاقها 
هلى هناك خطب ما؟ 
I will never contribute to the Arabic translation 
تعمدت الكتابة باللغة العربية.      :)

**Comment by Jeii20** [comment]
Please do not discuss this topic in the **Issues** tab. If you want to report something about translation, please go to [**ticket**](https://discord.com/channels/941543004026572811/942039671687479336) and open in category "Other". According to a lot of reviews, your changes didn't follow as expected, so this is the reason. As it says on the instructions: **Low qualitytranslations(those receiving a high number of comments compared to the number of translations done) will not receive a tag.**

**Comment by Jeii20** [comment]
And also, your PR has been closed because you marked a conversation as resolved without making the needed change, and that cannot be merged like that. You removed an essential character at PR #649. For next times, please pay attention to the requested changes and make them, and the conversations will automatically be marked as resolved. But instead, you did it by yourself without sending a new commit.

I hope this reason is clear enough, @Taki3600.
